{%set name = "Flask-Login" %}
{%set version = "0.3.2" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "e72eff5c35e5a31db1aeca1db5d2501be702674ea88e8f223b5d2b11644beee6" %}
{% set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - flask

  run:
    - python
    - flask

test:
  imports:
    - flask_login

about:
  home: https://github.com/maxcountryman/flask-login
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'User session management for Flask'
  dev_url: https://github.com/maxcountryman/flask-login
  doc_url: https://flask-login.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
