{% set name = "Flask-Login" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e23d14a607ef12806c699590b89d0f0e0d67baeec599d75947bf9c147330333

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - flask >=1.0.4
    - werkzeug >=1.0.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - flask_login

about:
  home: https://github.com/maxcountryman/flask-login
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: User session management for Flask
  description: |
    flask-login handles the common tasks  of logging in, logging out, and remembering your users'
    sessions over extended periods of time.
  doc_url: https://flask-login.readthedocs.io/
  dev_url: https://github.com/maxcountryman/flask-login

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
