{% set name = "Flask-Login" %}
{% set version = "0.5.0" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: 6d33aef15b5bcead780acc339464aae8a6e28f13c90d8b1cf9de8b549d1c0b4b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
    - flask

  run:
    - python
    - flask

test:
  imports:
    - flask_login

about:
  home: https://github.com/maxcountryman/flask-login
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'User session management for Flask'
  dev_url: https://github.com/maxcountryman/flask-login
  doc_url: https://flask-login.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
