{% set name = "Flask-Login" %}
{% set version = "0.6.2" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: c0a7baa9fdc448cdd3dd6f0939df72eec5177b2f7abe6cb82fc934d29caac9c3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - flask

  run:
    - python
    - flask

test:
  commands:
    - pip check
  imports:
    - flask_login

about:
  home: https://github.com/maxcountryman/flask-login
  license: MIT
  license_file: LICENSE
  summary: User session management for Flask
  description: |
    flask-login handles the common tasks  of logging in, logging out, and remembering your users'
    sessions over extended periods of time.
  doc_url: http://flask-login.readthedocs.org/en/latest/
  doc_source_url: https://github.com/maxcountryman/flask-login/blob/master/docs/index.rst
  dev_url: https://github.com/maxcountryman/flask-login

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
