travis:
  secure:
    BINSTAR_TOKEN: Imjrz2C+Cj7+t4SGZ0tplowA54y1V0Hv6hYSWGxgUh4cpEqMNU9yyG5+fRA/Yc3lgGV51BFy0Xx23RfThNEjFP5PiLj2VDkqrvunWEHHDoJIHl5hJSIgvnCKmtalEWl7GhQpAtcVQgWzN58V5kWLcOV7LKscx0OcKd0aZEsYAstvccpiUGsL+brZJ7M7UK5g+oiQUSuY06mivTvN3dh+B6UK19Xiezf2k1gDmrUGPqRiLKAYHe++S//Udz0Mxh0LlZWwFoMzS+VmWC0bThiv2o0hHElIQ8E1Hz8SVDZtEIibLTf4FmaVYg9AUNPQ7tdEd8CLE8sRh3BtJhFIeqb19uScEjvjx3+9NE/Ds2umsj5DI6mCk9ZVqkLio2THIpdM6ZuzQWckrMmEESC4xgMODowIAodgcdkzgK6Qa/NJ93IP943nrGKuVbvIGmZm8ymQSL+dgSE/3SdeE/04K8P7hTBGs40W2VKrf1S2IuOwP6QGWgFBeA8eNBJTgCaWwPJj4pbM33qytmD8HGk4KlyCMYKRuX+QSI/PGKM0V6DUeJV46VzAE6xRYeA54coqEiXZwYXyTuv4dGZA0uZ/qy+u/c9lRzbCsGa10KlPFEWf8fTHj/H0leqNA4UtZogT6Jj9mGCvlt1UApH1Pri/a8RJQwMaZGyhosapDJsNAQTK9v0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
